import SwiftUI
import UIKit

// MARK: - Hex initializer
extension Color {
    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let r, g, b: UInt64
        (r, g, b) = ((int >> 16) & 0xFF, (int >> 8) & 0xFF, int & 0xFF)
        self.init(
            .sRGB,
            red: Double(r) / 255,
            green: Double(g) / 255,
            blue: Double(b) / 255,
            opacity: 1
        )
    }
}

// MARK: - Raw palette
struct BrandPalette {
    struct Teal {
        static let s900 = Color(hex: "04342C")
        static let s800 = Color(hex: "085041")
        static let s700 = Color(hex: "0A4D3E")
        static let s600 = Color(hex: "0F6E56")
        static let s500 = Color(hex: "1D9E75")
        static let s400 = Color(hex: "2AB88A")
        static let s300 = Color(hex: "5DCAA5")
        static let s200 = Color(hex: "9FE1CB")
        static let s100 = Color(hex: "C8EFE0")
        static let s50  = Color(hex: "E1F5EE")
    }
    struct Amber {
        static let s900 = Color(hex: "412402")
        static let s800 = Color(hex: "633806")
        static let s700 = Color(hex: "854F0B")
        static let s600 = Color(hex: "BA7517")
        static let s500 = Color(hex: "E8A020")
        static let s400 = Color(hex: "F0B442")
        static let s300 = Color(hex: "FAC775")
        static let s200 = Color(hex: "FDDEA0")
        static let s100 = Color(hex: "FAEEDA")
        static let s50  = Color(hex: "FDF6EA")
    }
    struct Neutral {
        static let s900 = Color(hex: "1A1A18")
        static let s800 = Color(hex: "2C2C2A")
        static let s700 = Color(hex: "444441")
        static let s600 = Color(hex: "5F5E5A")
        static let s500 = Color(hex: "888780")
        static let s400 = Color(hex: "B4B2A9")
        static let s300 = Color(hex: "D3D1C7")
        static let s200 = Color(hex: "E8E6DE")
        static let s100 = Color(hex: "F2F0EA")
        static let s50  = Color(hex: "F7F5F0")
    }
    struct Status {
        static let success = Color(hex: "1D9E75")
        static let warning = Color(hex: "E8A020")
        static let danger  = Color(hex: "E24B4A")
        static let info    = Color(hex: "378ADD")
    }

    /// Accent companions from `color-preview.html` (Design Exploration).
    struct Exploration {
        static let warmCoral = Color(hex: "D4654A")
        static let softPlum = Color(hex: "7B6B8D")
    }
}

// MARK: - Semantic tokens (Asset Catalog backed — light/dark automatic)
// Xcode 16+ auto-generates Color.gsXxx from the asset catalog color sets,
// so we only declare tokens that are NOT in the catalog.
extension Color {
    /// Text/icons on **fixed** dark brand surfaces (teal hero fills, teal/amber gradient wells,
    /// `BrandPalette.Teal.s800` circles). Stays light in Dark Mode. Prefer **`gsTextInverse`**
    /// on **`gsBrandPrimary`** buttons — that color adapts (lighter in Dark Mode) and pairs with
    /// adaptive inverse text. The shopping list widget uses the same sRGB triple in
    /// `ShoppingListWidgetChrome.onDark` (widget target cannot import this module).
    static let gsTextOnBrand = Color(
        .sRGB,
        red: 0.949,
        green: 0.941,
        blue: 0.918,
        opacity: 1
    )
}

// Asset catalog colors (gsBackground, gsSurface, etc.) are auto-generated by
// Xcode 16+ and resolve in ShapeStyle contexts automatically.
// Only non-catalog tokens need a manual ShapeStyle shim.
extension ShapeStyle where Self == Color {
    static var gsTextOnBrand: Color { Color.gsTextOnBrand }
}

// UIKit colors (gsSurface, etc.) are auto-generated from the asset catalog by Xcode 16+.
