import Foundation

/// Maps grocery/pantry item names to emoji icons, falling back to category emoji,
/// then to an SF Symbol name if no emoji fits.
enum ItemIconMapper {

    // MARK: - Public API

    /// Returns the best emoji for a given item name and category.
    /// Priority: exact name match → keyword match → category emoji.
    static func emoji(for name: String, category: String = "") -> String {
        let key = name.lowercased().trimmingCharacters(in: .whitespaces)

        if let exact = itemEmoji[key] { return exact }

        for (keyword, icon) in keywordEmoji where containsWholeWord(key, word: keyword) {
            return icon
        }

        return categoryEmoji(for: category)
    }

    /// Category-level emoji fallback (used when no item-specific match is found).
    static func categoryEmoji(for category: String) -> String {
        switch category.lowercased() {
        case "fruits":           return "🍎"
        case "vegetables":       return "🥬"
        case "dairy":            return "🧀"
        case "meat":             return "🥩"
        case "seafood":          return "🐟"
        case "grains":           return "🌾"
        case "snacks":           return "🍿"
        case "beverages":        return "🥤"
        case "frozen":           return "🧊"
        case "condiments":       return "🧂"
        case "bakery":           return "🥐"
        case "canned":           return "🥫"
        case "african staples":  return "🍲"
        case "african spices":   return "🌶️"
        case "other":            return "🛒"
        default:                 return "🛒"
        }
    }

    /// SF Symbol fallback for contexts that need one (e.g. accessibility, widgets).
    static func sfSymbol(for category: String) -> String {
        switch category.lowercased() {
        case "fruits":           return "basket.fill"
        case "vegetables":       return "leaf.fill"
        case "dairy":            return "cup.and.saucer.fill"
        case "meat":             return "fork.knife"
        case "seafood":          return "fish.fill"
        case "grains":           return "circle.grid.3x3.fill"
        case "snacks":           return "popcorn.fill"
        case "beverages":        return "mug.fill"
        case "frozen":           return "snowflake"
        case "condiments":       return "flask.fill"
        case "bakery":           return "oven.fill"
        case "canned":           return "shippingbox.fill"
        case "african staples":  return "circle.hexagongrid.fill"
        case "african spices":   return "flame.fill"
        case "other":            return "bag.fill"
        default:                 return "cart.fill"
        }
    }

    // MARK: - Item → Emoji Dictionary

    // swiftlint:disable function_body_length
    private static let itemEmoji: [String: String] = [

        // ── Fruits ──────────────────────────────────────────────
        "apple":              "🍎",
        "banana":             "🍌",
        "orange":             "🍊",
        "strawberry":         "🍓",
        "blueberry":          "🫐",
        "raspberry":          "🫐",
        "grape":              "🍇",
        "mango":              "🥭",
        "pineapple":          "🍍",
        "watermelon":         "🍉",
        "lemon":              "🍋",
        "lime":               "🍋‍🟩",
        "avocado":            "🥑",
        "peach":              "🍑",
        "pear":               "🍐",
        "plum":               "🍑",
        "cherry":             "🍒",
        "kiwi":               "🥝",
        "coconut":            "🥥",
        "grapefruit":         "🍊",
        "blackberry":         "🫐",
        "cantaloupe":         "🍈",
        "honeydew":           "🍈",
        "papaya":             "🥭",
        "passion fruit":      "🍈",
        "dragon fruit":       "🐉",
        "pomegranate":        "🍎",
        "fig":                "🫒",
        "tangerine":          "🍊",
        "clementine":         "🍊",
        "nectarine":          "🍑",
        "apricot":            "🍑",
        "guava":              "🍈",
        "lychee":             "🍈",
        "star fruit":         "⭐",
        "plantain":           "🍌",
        "cranberry":          "🫐",
        "dates":              "🌴",
        "raisins":            "🍇",
        "dried mango":        "🥭",
        "blood orange":       "🍊",
        "jackfruit":          "🍈",
        "persimmon":          "🍊",

        // ── Vegetables ──────────────────────────────────────────
        "tomato":             "🍅",
        "potato":             "🥔",
        "onion":              "🧅",
        "garlic":             "🧄",
        "carrot":             "🥕",
        "broccoli":           "🥦",
        "spinach":            "🥬",
        "lettuce":            "🥬",
        "cucumber":           "🥒",
        "bell pepper":        "🫑",
        "mushroom":           "🍄",
        "zucchini":           "🥒",
        "sweet potato":       "🍠",
        "corn":               "🌽",
        "green beans":        "🫘",
        "cauliflower":        "🥦",
        "celery":             "🥬",
        "asparagus":          "🌿",
        "kale":               "🥬",
        "cabbage":            "🥬",
        "eggplant":           "🍆",
        "ginger":             "🫚",
        "jalapeño":           "🌶️",
        "radish":             "🥕",
        "beetroot":           "🟣",
        "red onion":          "🧅",
        "green onion":        "🧅",
        "shallot":            "🧅",
        "leek":               "🧅",
        "chive":              "🌿",
        "bok choy":           "🥬",
        "brussels sprouts":   "🥬",
        "artichoke":          "🌿",
        "fennel":             "🌿",
        "turnip":             "🥔",
        "parsnip":            "🥕",
        "butternut squash":   "🎃",
        "acorn squash":       "🎃",
        "spaghetti squash":   "🎃",
        "pumpkin":            "🎃",
        "okra":               "🌿",
        "swiss chard":        "🥬",
        "arugula":            "🥬",
        "romaine lettuce":    "🥬",
        "iceberg lettuce":    "🥬",
        "spring mix":         "🥗",
        "watercress":         "🌿",
        "collard greens":     "🥬",
        "endive":             "🥬",
        "radicchio":          "🥬",
        "snow peas":          "🫛",
        "sugar snap peas":    "🫛",
        "habanero":           "🌶️",
        "serrano pepper":     "🌶️",
        "poblano pepper":     "🫑",
        "anaheim pepper":     "🫑",
        "thai chili":         "🌶️",
        "daikon radish":      "🥕",
        "jicama":             "🥔",
        "taro":               "🥔",
        "yam":                "🍠",
        "cassava":            "🥔",
        "edamame":            "🫘",
        "bean sprouts":       "🌱",
        "baby corn":          "🌽",
        "water chestnut":     "🌰",
        "bamboo shoots":      "🎋",
        "bitter leaf":        "🌿",
        "ugu":                "🥬",
        "waterleaf":          "🌿",
        "scotch bonnet":      "🌶️",
        "garden eggs":        "🍆",
        "egusi":              "🌰",
        "ogbono":             "🌰",

        "fresh herbs (cilantro)":  "🌿",
        "fresh herbs (parsley)":   "🌿",
        "fresh herbs (mint)":      "🌿",
        "fresh herbs (rosemary)":  "🌿",
        "fresh herbs (thyme)":     "🌿",
        "fresh herbs (dill)":      "🌿",
        "fresh herbs (sage)":      "🌿",

        // ── Dairy ───────────────────────────────────────────────
        "whole milk":               "🥛",
        "semi-skimmed milk":        "🥛",
        "skimmed milk":             "🥛",
        "oat milk":                 "🥛",
        "almond milk":              "🥛",
        "soy milk":                 "🥛",
        "butter":                   "🧈",
        "cheddar cheese":           "🧀",
        "mozzarella":               "🧀",
        "parmesan":                 "🧀",
        "cream cheese":             "🧀",
        "feta cheese":              "🧀",
        "greek yogurt":             "🥛",
        "natural yogurt":           "🥛",
        "double cream":             "🍶",
        "single cream":             "🍶",
        "sour cream":               "🍶",
        "eggs":                     "🥚",
        "cottage cheese":           "🧀",
        "gouda cheese":             "🧀",
        "brie":                     "🧀",
        "swiss cheese":             "🧀",
        "provolone":                "🧀",
        "ricotta":                  "🧀",
        "mascarpone":               "🧀",
        "blue cheese":              "🧀",
        "havarti":                  "🧀",
        "pepper jack":              "🧀",
        "colby jack":               "🧀",
        "string cheese":            "🧀",
        "sliced american cheese":   "🧀",
        "shredded cheese":          "🧀",
        "whipped cream":            "🍦",
        "heavy cream":              "🍶",
        "half and half":            "🍶",
        "evaporated milk":          "🥛",
        "condensed milk":           "🥛",
        "coconut yogurt":           "🥥",
        "kefir":                    "🥛",
        "ghee":                     "🧈",
        "egg whites":               "🥚",
        "queso fresco":             "🧀",
        "paneer":                   "🧀",
        "labneh":                   "🥛",

        // ── Meat ────────────────────────────────────────────────
        "chicken breast":       "🍗",
        "chicken thigh":        "🍗",
        "whole chicken":        "🍗",
        "chicken wings":        "🍗",
        "chicken drumstick":    "🍗",
        "ground chicken":       "🍗",
        "chicken sausage":      "🌭",
        "rotisserie chicken":   "🍗",
        "ground beef":          "🥩",
        "beef steak":           "🥩",
        "beef roast":           "🥩",
        "ribeye steak":         "🥩",
        "t-bone steak":         "🥩",
        "filet mignon":         "🥩",
        "flank steak":          "🥩",
        "beef short ribs":      "🍖",
        "beef brisket":         "🍖",
        "stew beef":            "🥩",
        "corned beef":          "🥩",
        "beef mince":           "🥩",
        "pork chop":            "🍖",
        "pork loin":            "🍖",
        "pork tenderloin":      "🍖",
        "pork belly":           "🍖",
        "pork ribs":            "🍖",
        "ground pork":          "🍖",
        "bacon":                "🥓",
        "ham":                  "🍖",
        "sausage":              "🌭",
        "italian sausage":      "🌭",
        "bratwurst":            "🌭",
        "chorizo":              "🌭",
        "hot dog":              "🌭",
        "turkey breast":        "🦃",
        "ground turkey":        "🦃",
        "turkey sausage":       "🌭",
        "deli turkey":          "🦃",
        "deli ham":             "🍖",
        "roast beef deli":      "🥩",
        "lamb chop":            "🍖",
        "lamb leg":             "🍖",
        "ground lamb":          "🍖",
        "lamb shoulder":        "🍖",
        "rack of lamb":         "🍖",
        "veal cutlet":          "🥩",
        "bison burger":         "🦬",
        "duck breast":          "🦆",
        "salami":               "🍕",
        "pepperoni":            "🍕",
        "prosciutto":           "🍖",
        "pancetta":             "🥓",
        "canadian bacon":       "🥓",
        "liver":                "🫀",
        "ponmo":                "🍖",
        "shaki":                "🍖",
        "oxtail":               "🍖",
        "goat meat":            "🐐",

        // ── Seafood ─────────────────────────────────────────────
        "salmon fillet":            "🍣",
        "tuna steak":               "🐟",
        "canned tuna":              "🥫",
        "shrimp":                   "🦐",
        "cod fillet":               "🐟",
        "haddock":                  "🐟",
        "sea bass":                 "🐟",
        "tilapia":                  "🐟",
        "crab":                     "🦀",
        "lobster":                  "🦞",
        "mussels":                  "🦪",
        "sardines":                 "🐟",
        "anchovies":                "🐟",
        "calamari":                 "🦑",
        "clams":                    "🦪",
        "salmon (canned)":          "🥫",
        "canned sardines in oil":   "🥫",
        "canned sardines":          "🥫",
        "canned mackerel":          "🥫",
        "smoked salmon":            "🍣",
        "swordfish":                "🐟",
        "mahi mahi":                "🐟",
        "halibut":                  "🐟",
        "trout":                    "🐟",
        "catfish":                  "🐟",
        "red snapper":              "🐟",
        "scallops":                 "🦪",
        "oysters":                  "🦪",
        "crawfish":                 "🦞",
        "octopus":                  "🐙",
        "imitation crab":           "🦀",
        "fish sticks":              "🐟",
        "canned crab":              "🥫",
        "stockfish":                "🐟",
        "smoked fish":              "🐟",
        "dry fish":                 "🐟",

        // ── Grains & Pasta ──────────────────────────────────────
        "white rice":           "🍚",
        "brown rice":           "🍚",
        "basmati rice":         "🍚",
        "jasmine rice":         "🍚",
        "wild rice":            "🍚",
        "arborio rice":         "🍚",
        "sushi rice":           "🍚",
        "parboiled rice":       "🍚",
        "jollof rice":          "🍚",
        "spaghetti":            "🍝",
        "penne":                "🍝",
        "fusilli":              "🍝",
        "macaroni":             "🍝",
        "linguine":             "🍝",
        "lasagna sheets":       "🍝",
        "rigatoni":             "🍝",
        "farfalle":             "🍝",
        "orzo":                 "🍝",
        "gnocchi":              "🍝",
        "tortellini":           "🍝",
        "ravioli":              "🍝",
        "vermicelli":           "🍝",
        "rice noodles":         "🍜",
        "egg noodles":          "🍜",
        "ramen noodles":        "🍜",
        "udon noodles":         "🍜",
        "soba noodles":         "🍜",
        "white bread":          "🍞",
        "whole wheat bread":    "🍞",
        "sourdough bread":      "🍞",
        "pita bread":           "🫓",
        "ciabatta":             "🥖",
        "baguette":             "🥖",
        "tortilla":             "🫓",
        "naan bread":           "🫓",
        "english muffin":       "🧁",
        "hamburger buns":       "🍔",
        "hot dog buns":         "🌭",
        "croissant":            "🥐",
        "corn tortilla":        "🫓",
        "flour tortilla":       "🫓",
        "bagel":                "🥯",
        "oats":                 "🥣",
        "cornflakes":           "🥣",
        "granola":              "🥣",
        "muesli":               "🥣",
        "cream of wheat":       "🥣",
        "grits":                "🥣",
        "flour":                "🌾",
        "whole wheat flour":    "🌾",
        "almond flour":         "🌾",
        "coconut flour":        "🌾",
        "self-rising flour":    "🌾",
        "wheat flour":          "🌾",
        "couscous":             "🌾",
        "quinoa":               "🌾",
        "buckwheat":            "🌾",
        "bulgur":               "🌾",
        "farro":                "🌾",
        "barley":               "🌾",
        "polenta":              "🌽",
        "cornmeal":             "🌽",
        "breadcrumbs":          "🍞",
        "panko":                "🍞",
        "croutons":             "🍞",

        // ── Snacks ──────────────────────────────────────────────
        "potato chips":         "🍟",
        "tortilla chips":       "🌮",
        "popcorn":              "🍿",
        "pretzels":             "🥨",
        "trail mix":            "🥜",
        "almonds":              "🌰",
        "cashews":              "🌰",
        "peanuts":              "🥜",
        "walnuts":              "🌰",
        "pistachios":           "🌰",
        "pecans":               "🌰",
        "macadamia nuts":       "🌰",
        "hazelnuts":            "🌰",
        "mixed nuts":           "🥜",
        "groundnuts":           "🥜",
        "sunflower seeds":      "🌻",
        "pumpkin seeds":        "🎃",
        "chia seeds":           "🌱",
        "flax seeds":           "🌱",
        "dark chocolate":       "🍫",
        "milk chocolate":       "🍫",
        "white chocolate":      "🍫",
        "chocolate chips":      "🍫",
        "cookies":              "🍪",
        "crackers":             "🍘",
        "granola bar":          "🍫",
        "protein bar":          "💪",
        "dried fruit":          "🍇",
        "rice cakes":           "🍘",
        "hummus":               "🫕",
        "salsa":                "🫙",
        "guacamole":            "🥑",
        "beef jerky":           "🥩",
        "fruit snacks":         "🍬",
        "gummy bears":          "🍬",
        "marshmallows":         "🍬",
        "pork rinds":           "🍖",
        "cheese puffs":         "🧀",
        "veggie chips":         "🥬",
        "seaweed snacks":       "🌊",
        "animal crackers":      "🍪",
        "graham crackers":      "🍪",
        "rice crackers":        "🍘",
        "plantain chips":       "🍌",
        "chin chin":            "🍪",
        "puff puff mix":        "🧁",
        "kuli kuli":            "🥜",
        "suya":                 "🍢",
        "meat pie":             "🥧",
        "sausage roll":         "🌭",

        // ── Beverages ───────────────────────────────────────────
        "water":                "💧",
        "sparkling water":      "💧",
        "orange juice":         "🍊",
        "apple juice":          "🧃",
        "cranberry juice":      "🧃",
        "grape juice":          "🍇",
        "pineapple juice":      "🍍",
        "tomato juice":         "🍅",
        "v8 juice":             "🥤",
        "coffee beans":         "☕",
        "ground coffee":        "☕",
        "instant coffee":       "☕",
        "decaf coffee":         "☕",
        "espresso pods":        "☕",
        "black tea":            "🍵",
        "green tea":            "🍵",
        "herbal tea":           "🍵",
        "chai tea":             "🍵",
        "chamomile tea":        "🍵",
        "matcha powder":        "🍵",
        "cola":                 "🥤",
        "lemonade":             "🍋",
        "coconut water":        "🥥",
        "sports drink":         "🥤",
        "smoothie":             "🥤",
        "ginger ale":           "🥤",
        "root beer":            "🍺",
        "tonic water":          "💧",
        "club soda":            "💧",
        "energy drink":         "⚡",
        "kombucha":             "🍵",
        "hot cocoa mix":        "🍫",
        "lemon juice (bottled)": "🍋",
        "protein shake":        "💪",
        "malta guinness":       "🍺",
        "amstel malta":         "🍺",
        "chapman":              "🍹",
        "zobo":                 "🌺",
        "milo":                 "🍫",
        "ovaltine":             "🍫",

        // ── Frozen ──────────────────────────────────────────────
        "frozen pizza":                 "🍕",
        "frozen peas":                  "🫛",
        "frozen corn":                  "🌽",
        "frozen broccoli":              "🥦",
        "frozen mixed vegetables":      "🥗",
        "frozen berries":               "🫐",
        "frozen strawberries":          "🍓",
        "frozen mango":                 "🥭",
        "frozen spinach":               "🥬",
        "frozen edamame":               "🫘",
        "frozen stir fry mix":          "🥡",
        "fish fingers":                 "🐟",
        "frozen chicken nuggets":       "🍗",
        "frozen french fries":          "🍟",
        "ice cream":                    "🍦",
        "frozen waffles":               "🧇",
        "frozen dumplings":             "🥟",
        "frozen shrimp":                "🦐",
        "frozen bread rolls":           "🍞",
        "frozen burrito":               "🌯",
        "frozen lasagna":               "🍝",
        "frozen mac and cheese":        "🧀",
        "frozen pot pie":               "🥧",
        "frozen breakfast sandwich":    "🥪",
        "frozen pancakes":              "🥞",
        "frozen hash browns":           "🥔",
        "frozen onion rings":           "🧅",
        "frozen mozzarella sticks":     "🧀",
        "frozen spring rolls":          "🥟",
        "frozen pie crust":             "🥧",
        "frozen puff pastry":           "🥐",
        "frozen cookie dough":          "🍪",
        "frozen yogurt":                "🍦",
        "sorbet":                       "🍧",
        "ice cream sandwich":           "🍦",
        "popsicle":                     "🍧",

        // ── Condiments & Spices ─────────────────────────────────
        "olive oil":                "🫒",
        "vegetable oil":            "🛢️",
        "coconut oil":              "🥥",
        "sesame oil":               "🫘",
        "avocado oil":              "🥑",
        "truffle oil":              "🍄",
        "palm oil":                 "🌴",
        "red palm oil":             "🌴",
        "groundnut oil":            "🥜",
        "soy sauce":                "🫙",
        "ketchup":                  "🍅",
        "mustard":                  "🌭",
        "mayonnaise":               "🫙",
        "hot sauce":                "🌶️",
        "sriracha":                 "🌶️",
        "vinegar":                  "🫙",
        "balsamic vinegar":         "🫙",
        "apple cider vinegar":      "🍎",
        "rice vinegar":             "🍚",
        "red wine vinegar":         "🍷",
        "honey":                    "🍯",
        "maple syrup":              "🍁",
        "agave syrup":              "🌵",
        "salt":                     "🧂",
        "black pepper":             "🫚",
        "paprika":                  "🌶️",
        "cumin":                    "🌿",
        "cinnamon":                 "🌿",
        "turmeric":                 "🟡",
        "chili powder":             "🌶️",
        "garlic powder":            "🧄",
        "onion powder":             "🧅",
        "oregano":                  "🌿",
        "basil":                    "🌿",
        "italian seasoning":        "🌿",
        "taco seasoning":           "🌮",
        "cajun seasoning":          "🌶️",
        "bay leaves":               "🍃",
        "nutmeg":                   "🌰",
        "cloves":                   "🌿",
        "cardamom":                 "🌿",
        "coriander":                "🌿",
        "fennel seeds":             "🌿",
        "red pepper flakes":        "🌶️",
        "tomato paste":             "🍅",
        "worcestershire sauce":     "🫙",
        "bbq sauce":                "🍖",
        "fish sauce":               "🐟",
        "oyster sauce":             "🦪",
        "hoisin sauce":             "🫙",
        "teriyaki sauce":           "🥢",
        "steak sauce":              "🥩",
        "tartar sauce":             "🐟",
        "peanut butter":            "🥜",
        "almond butter":            "🌰",
        "sunflower butter":         "🌻",
        "jam":                      "🫙",
        "marmalade":                "🍊",
        "nutella":                  "🍫",
        "tahini":                   "🫘",
        "harissa":                  "🌶️",
        "gochujang":                "🌶️",
        "miso paste":               "🥢",
        "curry paste":              "🍛",
        "dijon mustard":            "🌭",
        "whole grain mustard":      "🌭",
        "ranch dressing":           "🥗",
        "italian dressing":         "🥗",
        "caesar dressing":          "🥗",
        "thousand island":          "🥗",
        "relish":                   "🫙",
        "capers":                   "🫒",
        "olives":                   "🫒",
        "pickles":                  "🥒",
        "sauerkraut":               "🥬",
        "kimchi":                   "🌶️",

        // ── African Staples ─────────────────────────────────────
        "fufu flour":           "🍲",
        "garri":                "🍲",
        "eba":                  "🍲",
        "pounded yam flour":    "🍲",
        "semolina":             "🌾",
        "oatmeal pap":          "🥣",

        // ── African Spices ──────────────────────────────────────
        "suya spice":           "🌶️",
        "yaji":                 "🌶️",
        "maggi cubes":          "🧊",
        "knorr cubes":          "🧊",
        "ground crayfish":      "🦐",
        "dry pepper":           "🌶️",
        "alligator pepper":     "🌶️",
        "ehuru":                "🌰",
        "uziza":                "🌿",
        "utazi":                "🌿",
        "scent leaves":         "🌿",

        // ── Other / Pantry Staples ──────────────────────────────
        "sugar":                    "🍬",
        "brown sugar":              "🍬",
        "powdered sugar":           "🍬",
        "baking powder":            "🧪",
        "baking soda":              "🧪",
        "vanilla extract":          "🌿",
        "almond extract":           "🌿",
        "peppermint extract":       "🌿",
        "cocoa powder":             "🍫",
        "cornstarch":               "🌽",
        "gelatin":                  "🍮",
        "yeast":                    "🍞",
        "cream of tartar":          "🧪",
        "food coloring":            "🎨",
        "canned tomatoes":          "🥫",
        "diced tomatoes":           "🥫",
        "crushed tomatoes":         "🥫",
        "tomato sauce":             "🥫",
        "marinara sauce":           "🍝",
        "alfredo sauce":            "🍝",
        "pesto":                    "🌿",
        "salsa verde":              "🫙",
        "enchilada sauce":          "🌮",
        "canned beans":             "🥫",
        "canned black beans":       "🥫",
        "canned kidney beans":      "🥫",
        "canned pinto beans":       "🥫",
        "canned white beans":       "🥫",
        "canned corn":              "🥫",
        "canned green beans":       "🥫",
        "canned peas":              "🥫",
        "canned pumpkin":           "🥫",
        "canned coconut cream":     "🥥",
        "canned soup":              "🥫",
        "chickpeas":                "🫘",
        "lentils":                  "🫘",
        "dried black beans":        "🫘",
        "dried chickpeas":          "🫘",
        "split peas":               "🫘",
        "black-eyed peas":          "🫘",
        "honey beans":              "🫘",
        "brown beans":              "🫘",
        "coconut milk":             "🥥",
        "chicken broth":            "🍲",
        "vegetable broth":          "🍲",
        "beef broth":               "🍲",
        "bone broth":               "🍲",
        "tofu":                     "🍱",
        "tempeh":                   "🍱",
        "seitan":                   "🍱",
        "beyond meat":              "🌱",
        "protein powder":           "💪",
        "nutritional yeast":        "🌿",
        "tapioca starch":           "🌾",
        "arrowroot powder":         "🌾",
        "soy sauce (low sodium)":   "🫙",
        "coconut aminos":           "🥥",
        "rice paper":               "🥢",
        "wonton wrappers":          "🥟",
        "spring roll wrappers":     "🥟",
        "phyllo dough":             "🥐",
        "indomie":                  "🍜",

        // ── Household ───────────────────────────────────────────
        "paper towels":         "🧻",
        "dish soap":            "🧴",
        "trash bags":           "🗑️",
        "aluminum foil":        "🪩",
        "plastic wrap":         "📦",
        "parchment paper":      "📜",
        "zip lock bags":        "📦",
        "sponge":               "🧽",
        "laundry detergent":    "🧺",
        "all-purpose cleaner":  "🧴",
        "hand soap":            "🧴",
        "dishwasher pods":      "🫧",
        "paper napkins":        "🧻",
        "toilet paper":         "🧻",
        "tissues":              "🧻",
    ]
    // swiftlint:enable function_body_length

    /// Matches a keyword only on word boundaries (so "water" does not match inside "watermelon").
    private static func containsWholeWord(_ text: String, word: String) -> Bool {
        guard !word.isEmpty else { return false }
        var start = text.startIndex
        while start < text.endIndex {
            guard let range = text.range(of: word, range: start..<text.endIndex) else { return false }
            let beforeOk = range.lowerBound == text.startIndex || !text[text.index(before: range.lowerBound)].isLetter
            let afterOk = range.upperBound == text.endIndex || !text[range.upperBound].isLetter
            if beforeOk && afterOk { return true }
            start = range.upperBound
        }
        return false
    }

    // MARK: - Keyword Fallback (order matters — more specific first)

    private static let keywordEmoji: [(String, String)] = [
        ("chicken",     "🍗"),
        ("beef",        "🥩"),
        ("pork",        "🍖"),
        ("lamb",        "🍖"),
        ("turkey",      "🦃"),
        ("duck",        "🦆"),
        ("sausage",     "🌭"),
        ("bacon",       "🥓"),
        ("fish",        "🐟"),
        ("salmon",      "🍣"),
        ("shrimp",      "🦐"),
        ("crab",        "🦀"),
        ("lobster",     "🦞"),
        ("oyster",      "🦪"),
        ("cheese",      "🧀"),
        ("milk",        "🥛"),
        ("yogurt",      "🥛"),
        ("cream",       "🍶"),
        ("egg",         "🥚"),
        ("butter",      "🧈"),
        ("bread",       "🍞"),
        ("rice",        "🍚"),
        ("pasta",       "🍝"),
        ("noodle",      "🍜"),
        ("pizza",       "🍕"),
        ("burger",      "🍔"),
        ("taco",        "🌮"),
        ("burrito",     "🌯"),
        ("sandwich",    "🥪"),
        ("soup",        "🍲"),
        ("salad",       "🥗"),
        ("chocolate",   "🍫"),
        ("cookie",      "🍪"),
        ("cake",        "🎂"),
        ("pie",         "🥧"),
        ("waffle",      "🧇"),
        ("pancake",     "🥞"),
        ("ice cream",   "🍦"),
        ("coffee",      "☕"),
        ("tea",         "🍵"),
        ("juice",       "🧃"),
        ("soda",        "🥤"),
        ("water",       "💧"),
        ("wine",        "🍷"),
        ("beer",        "🍺"),
        ("pepper",      "🌶️"),
        ("herb",        "🌿"),
        ("spice",       "🌿"),
        ("oil",         "🛢️"),
        ("sauce",       "🫙"),
        ("vinegar",     "🫙"),
        ("nut",         "🥜"),
        ("seed",        "🌱"),
        ("bean",        "🫘"),
        ("lentil",      "🫘"),
        ("fruit",       "🍎"),
        ("vegetable",   "🥬"),
        ("frozen",      "🧊"),
        ("canned",      "🥫"),
        ("dried",       "🌿"),
        ("flour",       "🌾"),
        ("sugar",       "🍬"),
        ("honey",       "🍯"),
        ("soap",        "🧴"),
        ("clean",       "🧽"),
        ("paper",       "🧻"),
    ]
}
