-- GrubShelf Migration 003: Seed Grocery Catalog
-- 200+ common grocery items across all predefined categories

INSERT INTO grocery_catalog (name, default_category, default_unit, search_keywords) VALUES
-- Fruits
('Apple', 'Fruits', 'pcs', 'fruit red green'),
('Banana', 'Fruits', 'pcs', 'fruit yellow'),
('Orange', 'Fruits', 'pcs', 'fruit citrus'),
('Strawberry', 'Fruits', 'pcs', 'fruit berry'),
('Blueberry', 'Fruits', 'pcs', 'fruit berry'),
('Raspberry', 'Fruits', 'pcs', 'fruit berry'),
('Grape', 'Fruits', 'kg', 'fruit'),
('Mango', 'Fruits', 'pcs', 'fruit tropical'),
('Pineapple', 'Fruits', 'pcs', 'fruit tropical'),
('Watermelon', 'Fruits', 'pcs', 'fruit melon'),
('Lemon', 'Fruits', 'pcs', 'fruit citrus'),
('Lime', 'Fruits', 'pcs', 'fruit citrus'),
('Avocado', 'Fruits', 'pcs', 'fruit'),
('Peach', 'Fruits', 'pcs', 'fruit stone'),
('Pear', 'Fruits', 'pcs', 'fruit'),
('Plum', 'Fruits', 'pcs', 'fruit stone'),
('Cherry', 'Fruits', 'kg', 'fruit stone'),
('Kiwi', 'Fruits', 'pcs', 'fruit tropical'),
('Coconut', 'Fruits', 'pcs', 'fruit tropical'),
('Grapefruit', 'Fruits', 'pcs', 'fruit citrus'),

-- Vegetables
('Tomato', 'Vegetables', 'pcs', 'vegetable red'),
('Potato', 'Vegetables', 'kg', 'vegetable starch'),
('Onion', 'Vegetables', 'pcs', 'vegetable'),
('Garlic', 'Vegetables', 'pcs', 'vegetable'),
('Carrot', 'Vegetables', 'pcs', 'vegetable root'),
('Broccoli', 'Vegetables', 'pcs', 'vegetable green'),
('Spinach', 'Vegetables', 'g', 'vegetable leafy green'),
('Lettuce', 'Vegetables', 'pcs', 'vegetable leafy green salad'),
('Cucumber', 'Vegetables', 'pcs', 'vegetable green'),
('Bell Pepper', 'Vegetables', 'pcs', 'vegetable pepper capsicum'),
('Mushroom', 'Vegetables', 'g', 'vegetable fungi'),
('Zucchini', 'Vegetables', 'pcs', 'vegetable squash'),
('Sweet Potato', 'Vegetables', 'kg', 'vegetable starch'),
('Corn', 'Vegetables', 'pcs', 'vegetable'),
('Green Beans', 'Vegetables', 'g', 'vegetable'),
('Cauliflower', 'Vegetables', 'pcs', 'vegetable'),
('Celery', 'Vegetables', 'pcs', 'vegetable stalk'),
('Asparagus', 'Vegetables', 'g', 'vegetable'),
('Kale', 'Vegetables', 'g', 'vegetable leafy green'),
('Cabbage', 'Vegetables', 'pcs', 'vegetable'),
('Eggplant', 'Vegetables', 'pcs', 'vegetable aubergine'),
('Ginger', 'Vegetables', 'g', 'vegetable root spice'),
('Jalapeño', 'Vegetables', 'pcs', 'vegetable pepper hot'),
('Radish', 'Vegetables', 'pcs', 'vegetable root'),
('Beetroot', 'Vegetables', 'pcs', 'vegetable root'),

-- Dairy
('Whole Milk', 'Dairy', 'l', 'dairy milk'),
('Semi-Skimmed Milk', 'Dairy', 'l', 'dairy milk low fat'),
('Skimmed Milk', 'Dairy', 'l', 'dairy milk fat free'),
('Oat Milk', 'Dairy', 'l', 'dairy alternative plant milk'),
('Almond Milk', 'Dairy', 'l', 'dairy alternative plant milk'),
('Butter', 'Dairy', 'g', 'dairy spread'),
('Cheddar Cheese', 'Dairy', 'g', 'dairy cheese'),
('Mozzarella', 'Dairy', 'g', 'dairy cheese italian'),
('Parmesan', 'Dairy', 'g', 'dairy cheese italian hard'),
('Cream Cheese', 'Dairy', 'g', 'dairy cheese spread'),
('Feta Cheese', 'Dairy', 'g', 'dairy cheese greek'),
('Greek Yogurt', 'Dairy', 'g', 'dairy yogurt'),
('Natural Yogurt', 'Dairy', 'g', 'dairy yogurt plain'),
('Double Cream', 'Dairy', 'ml', 'dairy cream'),
('Single Cream', 'Dairy', 'ml', 'dairy cream'),
('Sour Cream', 'Dairy', 'ml', 'dairy cream'),
('Eggs', 'Dairy', 'pcs', 'dairy eggs protein'),
('Cottage Cheese', 'Dairy', 'g', 'dairy cheese'),
('Gouda Cheese', 'Dairy', 'g', 'dairy cheese dutch'),
('Brie', 'Dairy', 'g', 'dairy cheese french soft'),

-- Meat
('Chicken Breast', 'Meat', 'kg', 'meat poultry'),
('Chicken Thigh', 'Meat', 'kg', 'meat poultry'),
('Whole Chicken', 'Meat', 'kg', 'meat poultry'),
('Chicken Wings', 'Meat', 'kg', 'meat poultry'),
('Ground Beef', 'Meat', 'kg', 'meat mince'),
('Beef Steak', 'Meat', 'kg', 'meat steak sirloin'),
('Beef Roast', 'Meat', 'kg', 'meat roast'),
('Pork Chop', 'Meat', 'kg', 'meat pork'),
('Pork Loin', 'Meat', 'kg', 'meat pork'),
('Bacon', 'Meat', 'g', 'meat pork breakfast'),
('Ham', 'Meat', 'g', 'meat pork deli'),
('Sausage', 'Meat', 'pcs', 'meat pork'),
('Turkey Breast', 'Meat', 'kg', 'meat poultry deli'),
('Ground Turkey', 'Meat', 'kg', 'meat poultry mince'),
('Lamb Chop', 'Meat', 'kg', 'meat lamb'),
('Lamb Leg', 'Meat', 'kg', 'meat lamb roast'),
('Salami', 'Meat', 'g', 'meat deli italian'),
('Pepperoni', 'Meat', 'g', 'meat deli italian'),
('Prosciutto', 'Meat', 'g', 'meat deli italian'),
('Beef Mince', 'Meat', 'kg', 'meat ground'),

-- Seafood
('Salmon Fillet', 'Seafood', 'kg', 'fish seafood'),
('Tuna Steak', 'Seafood', 'kg', 'fish seafood'),
('Canned Tuna', 'Seafood', 'pcs', 'fish seafood tinned'),
('Shrimp', 'Seafood', 'kg', 'seafood prawn shellfish'),
('Cod Fillet', 'Seafood', 'kg', 'fish seafood white'),
('Haddock', 'Seafood', 'kg', 'fish seafood white'),
('Sea Bass', 'Seafood', 'kg', 'fish seafood'),
('Tilapia', 'Seafood', 'kg', 'fish seafood white'),
('Crab', 'Seafood', 'kg', 'seafood shellfish'),
('Lobster', 'Seafood', 'kg', 'seafood shellfish'),
('Mussels', 'Seafood', 'kg', 'seafood shellfish'),
('Sardines', 'Seafood', 'pcs', 'fish seafood tinned'),
('Anchovies', 'Seafood', 'g', 'fish seafood'),
('Calamari', 'Seafood', 'kg', 'seafood squid'),
('Clams', 'Seafood', 'kg', 'seafood shellfish'),

-- Grains
('White Rice', 'Grains', 'kg', 'grain rice'),
('Brown Rice', 'Grains', 'kg', 'grain rice whole'),
('Basmati Rice', 'Grains', 'kg', 'grain rice'),
('Jasmine Rice', 'Grains', 'kg', 'grain rice'),
('Spaghetti', 'Grains', 'g', 'grain pasta'),
('Penne', 'Grains', 'g', 'grain pasta'),
('Fusilli', 'Grains', 'g', 'grain pasta'),
('Macaroni', 'Grains', 'g', 'grain pasta'),
('Linguine', 'Grains', 'g', 'grain pasta'),
('Lasagna Sheets', 'Grains', 'g', 'grain pasta'),
('White Bread', 'Grains', 'pcs', 'grain bread'),
('Whole Wheat Bread', 'Grains', 'pcs', 'grain bread whole'),
('Sourdough Bread', 'Grains', 'pcs', 'grain bread'),
('Tortilla', 'Grains', 'pcs', 'grain wrap flatbread'),
('Naan Bread', 'Grains', 'pcs', 'grain bread indian'),
('Oats', 'Grains', 'kg', 'grain cereal breakfast'),
('Cornflakes', 'Grains', 'g', 'grain cereal breakfast'),
('Granola', 'Grains', 'g', 'grain cereal breakfast'),
('Flour', 'Grains', 'kg', 'grain baking'),
('Couscous', 'Grains', 'g', 'grain'),
('Quinoa', 'Grains', 'g', 'grain seed'),
('Bagel', 'Grains', 'pcs', 'grain bread'),

-- Snacks
('Potato Chips', 'Snacks', 'g', 'snack crisp'),
('Tortilla Chips', 'Snacks', 'g', 'snack nacho'),
('Popcorn', 'Snacks', 'g', 'snack'),
('Pretzels', 'Snacks', 'g', 'snack'),
('Trail Mix', 'Snacks', 'g', 'snack nuts'),
('Almonds', 'Snacks', 'g', 'snack nut'),
('Cashews', 'Snacks', 'g', 'snack nut'),
('Peanuts', 'Snacks', 'g', 'snack nut'),
('Walnuts', 'Snacks', 'g', 'snack nut'),
('Dark Chocolate', 'Snacks', 'g', 'snack chocolate'),
('Milk Chocolate', 'Snacks', 'g', 'snack chocolate'),
('Cookies', 'Snacks', 'pcs', 'snack biscuit'),
('Crackers', 'Snacks', 'g', 'snack'),
('Granola Bar', 'Snacks', 'pcs', 'snack energy bar'),
('Dried Fruit', 'Snacks', 'g', 'snack fruit'),
('Rice Cakes', 'Snacks', 'pcs', 'snack'),
('Hummus', 'Snacks', 'g', 'snack dip chickpea'),
('Salsa', 'Snacks', 'g', 'snack dip tomato'),
('Guacamole', 'Snacks', 'g', 'snack dip avocado'),

-- Beverages
('Water', 'Beverages', 'l', 'beverage drink'),
('Sparkling Water', 'Beverages', 'l', 'beverage drink carbonated'),
('Orange Juice', 'Beverages', 'l', 'beverage juice'),
('Apple Juice', 'Beverages', 'l', 'beverage juice'),
('Cranberry Juice', 'Beverages', 'l', 'beverage juice'),
('Coffee Beans', 'Beverages', 'g', 'beverage coffee'),
('Ground Coffee', 'Beverages', 'g', 'beverage coffee'),
('Instant Coffee', 'Beverages', 'g', 'beverage coffee'),
('Black Tea', 'Beverages', 'pcs', 'beverage tea bags'),
('Green Tea', 'Beverages', 'pcs', 'beverage tea bags'),
('Herbal Tea', 'Beverages', 'pcs', 'beverage tea bags'),
('Cola', 'Beverages', 'l', 'beverage soda'),
('Lemonade', 'Beverages', 'l', 'beverage'),
('Coconut Water', 'Beverages', 'l', 'beverage drink'),
('Sports Drink', 'Beverages', 'l', 'beverage energy'),
('Smoothie', 'Beverages', 'ml', 'beverage fruit'),

-- Frozen
('Frozen Pizza', 'Frozen', 'pcs', 'frozen meal'),
('Frozen Peas', 'Frozen', 'g', 'frozen vegetable'),
('Frozen Corn', 'Frozen', 'g', 'frozen vegetable'),
('Frozen Broccoli', 'Frozen', 'g', 'frozen vegetable'),
('Frozen Mixed Vegetables', 'Frozen', 'g', 'frozen vegetable'),
('Frozen Berries', 'Frozen', 'g', 'frozen fruit'),
('Frozen Strawberries', 'Frozen', 'g', 'frozen fruit'),
('Fish Fingers', 'Frozen', 'pcs', 'frozen fish'),
('Frozen Chicken Nuggets', 'Frozen', 'g', 'frozen meat poultry'),
('Frozen French Fries', 'Frozen', 'g', 'frozen potato chips'),
('Ice Cream', 'Frozen', 'ml', 'frozen dessert'),
('Frozen Waffles', 'Frozen', 'pcs', 'frozen breakfast'),
('Frozen Dumplings', 'Frozen', 'g', 'frozen meal asian'),
('Frozen Shrimp', 'Frozen', 'g', 'frozen seafood'),
('Frozen Bread Rolls', 'Frozen', 'pcs', 'frozen bread'),

-- Condiments
('Olive Oil', 'Condiments', 'ml', 'condiment oil cooking'),
('Vegetable Oil', 'Condiments', 'ml', 'condiment oil cooking'),
('Coconut Oil', 'Condiments', 'ml', 'condiment oil cooking'),
('Soy Sauce', 'Condiments', 'ml', 'condiment sauce asian'),
('Ketchup', 'Condiments', 'ml', 'condiment sauce tomato'),
('Mustard', 'Condiments', 'ml', 'condiment sauce'),
('Mayonnaise', 'Condiments', 'ml', 'condiment sauce'),
('Hot Sauce', 'Condiments', 'ml', 'condiment sauce spicy'),
('Vinegar', 'Condiments', 'ml', 'condiment'),
('Balsamic Vinegar', 'Condiments', 'ml', 'condiment'),
('Honey', 'Condiments', 'g', 'condiment sweetener'),
('Maple Syrup', 'Condiments', 'ml', 'condiment sweetener'),
('Salt', 'Condiments', 'g', 'condiment seasoning'),
('Black Pepper', 'Condiments', 'g', 'condiment seasoning spice'),
('Paprika', 'Condiments', 'g', 'condiment seasoning spice'),
('Cumin', 'Condiments', 'g', 'condiment seasoning spice'),
('Cinnamon', 'Condiments', 'g', 'condiment seasoning spice'),
('Oregano', 'Condiments', 'g', 'condiment herb'),
('Basil', 'Condiments', 'g', 'condiment herb'),
('Tomato Paste', 'Condiments', 'g', 'condiment sauce tomato'),
('Worcestershire Sauce', 'Condiments', 'ml', 'condiment sauce'),
('BBQ Sauce', 'Condiments', 'ml', 'condiment sauce'),
('Peanut Butter', 'Condiments', 'g', 'condiment spread'),
('Jam', 'Condiments', 'g', 'condiment spread'),
('Nutella', 'Condiments', 'g', 'condiment spread chocolate'),

-- Other
('Sugar', 'Other', 'kg', 'baking sweetener'),
('Brown Sugar', 'Other', 'kg', 'baking sweetener'),
('Baking Powder', 'Other', 'g', 'baking'),
('Baking Soda', 'Other', 'g', 'baking'),
('Vanilla Extract', 'Other', 'ml', 'baking flavoring'),
('Cocoa Powder', 'Other', 'g', 'baking chocolate'),
('Cornstarch', 'Other', 'g', 'baking thickener'),
('Gelatin', 'Other', 'g', 'baking'),
('Canned Tomatoes', 'Other', 'pcs', 'tinned tomato'),
('Canned Beans', 'Other', 'pcs', 'tinned legume'),
('Chickpeas', 'Other', 'pcs', 'tinned legume'),
('Lentils', 'Other', 'g', 'legume'),
('Coconut Milk', 'Other', 'ml', 'tinned cooking asian'),
('Chicken Broth', 'Other', 'ml', 'stock soup'),
('Vegetable Broth', 'Other', 'ml', 'stock soup'),
('Tofu', 'Other', 'g', 'protein plant soy'),
('Tempeh', 'Other', 'g', 'protein plant soy'),
('Paper Towels', 'Other', 'pcs', 'household cleaning'),
('Dish Soap', 'Other', 'ml', 'household cleaning'),
('Trash Bags', 'Other', 'pcs', 'household cleaning');
