-- FoodPan Migration 005: Expand Grocery Catalog
-- Adds ~300 more items across all categories + new categories (Baby, Pet, Health, Bakery, Deli, Canned/Jarred, Household)

INSERT INTO grocery_catalog (name, default_category, default_unit, search_keywords) VALUES

-- ===================== MORE FRUITS =====================
('Blackberry', 'Fruits', 'pcs', 'fruit berry'),
('Cantaloupe', 'Fruits', 'pcs', 'fruit melon'),
('Honeydew', 'Fruits', 'pcs', 'fruit melon'),
('Papaya', 'Fruits', 'pcs', 'fruit tropical'),
('Passion Fruit', 'Fruits', 'pcs', 'fruit tropical'),
('Dragon Fruit', 'Fruits', 'pcs', 'fruit tropical pitaya'),
('Pomegranate', 'Fruits', 'pcs', 'fruit'),
('Fig', 'Fruits', 'pcs', 'fruit'),
('Tangerine', 'Fruits', 'pcs', 'fruit citrus mandarin'),
('Clementine', 'Fruits', 'pcs', 'fruit citrus mandarin'),
('Nectarine', 'Fruits', 'pcs', 'fruit stone'),
('Apricot', 'Fruits', 'pcs', 'fruit stone'),
('Guava', 'Fruits', 'pcs', 'fruit tropical'),
('Lychee', 'Fruits', 'pcs', 'fruit tropical asian'),
('Star Fruit', 'Fruits', 'pcs', 'fruit tropical carambola'),
('Plantain', 'Fruits', 'pcs', 'fruit cooking banana'),
('Cranberry', 'Fruits', 'g', 'fruit berry'),
('Dates', 'Fruits', 'g', 'fruit dried'),
('Raisins', 'Fruits', 'g', 'fruit dried grape'),
('Dried Mango', 'Fruits', 'g', 'fruit dried tropical'),
('Frozen Mango', 'Fruits', 'g', 'fruit frozen tropical'),
('Blood Orange', 'Fruits', 'pcs', 'fruit citrus'),
('Jackfruit', 'Fruits', 'pcs', 'fruit tropical'),
('Persimmon', 'Fruits', 'pcs', 'fruit'),

-- ===================== MORE VEGETABLES =====================
('Red Onion', 'Vegetables', 'pcs', 'vegetable'),
('Green Onion', 'Vegetables', 'pcs', 'vegetable scallion'),
('Shallot', 'Vegetables', 'pcs', 'vegetable'),
('Leek', 'Vegetables', 'pcs', 'vegetable'),
('Chive', 'Vegetables', 'g', 'vegetable herb'),
('Bok Choy', 'Vegetables', 'pcs', 'vegetable asian leafy'),
('Brussels Sprouts', 'Vegetables', 'g', 'vegetable'),
('Artichoke', 'Vegetables', 'pcs', 'vegetable'),
('Fennel', 'Vegetables', 'pcs', 'vegetable'),
('Turnip', 'Vegetables', 'pcs', 'vegetable root'),
('Parsnip', 'Vegetables', 'pcs', 'vegetable root'),
('Butternut Squash', 'Vegetables', 'pcs', 'vegetable squash'),
('Acorn Squash', 'Vegetables', 'pcs', 'vegetable squash'),
('Spaghetti Squash', 'Vegetables', 'pcs', 'vegetable squash'),
('Pumpkin', 'Vegetables', 'pcs', 'vegetable squash'),
('Okra', 'Vegetables', 'g', 'vegetable'),
('Swiss Chard', 'Vegetables', 'g', 'vegetable leafy green'),
('Arugula', 'Vegetables', 'g', 'vegetable leafy green rocket salad'),
('Romaine Lettuce', 'Vegetables', 'pcs', 'vegetable leafy green salad'),
('Iceberg Lettuce', 'Vegetables', 'pcs', 'vegetable leafy green salad'),
('Spring Mix', 'Vegetables', 'g', 'vegetable leafy green salad'),
('Watercress', 'Vegetables', 'g', 'vegetable leafy green'),
('Collard Greens', 'Vegetables', 'g', 'vegetable leafy green'),
('Endive', 'Vegetables', 'pcs', 'vegetable leafy'),
('Radicchio', 'Vegetables', 'pcs', 'vegetable leafy'),
('Snow Peas', 'Vegetables', 'g', 'vegetable pea'),
('Sugar Snap Peas', 'Vegetables', 'g', 'vegetable pea'),
('Habanero', 'Vegetables', 'pcs', 'vegetable pepper hot'),
('Serrano Pepper', 'Vegetables', 'pcs', 'vegetable pepper hot'),
('Poblano Pepper', 'Vegetables', 'pcs', 'vegetable pepper'),
('Anaheim Pepper', 'Vegetables', 'pcs', 'vegetable pepper'),
('Thai Chili', 'Vegetables', 'pcs', 'vegetable pepper hot asian'),
('Daikon Radish', 'Vegetables', 'pcs', 'vegetable root asian'),
('Jicama', 'Vegetables', 'pcs', 'vegetable root'),
('Taro', 'Vegetables', 'pcs', 'vegetable root'),
('Yam', 'Vegetables', 'pcs', 'vegetable root starch'),
('Cassava', 'Vegetables', 'pcs', 'vegetable root starch yuca'),
('Edamame', 'Vegetables', 'g', 'vegetable soy bean'),
('Bean Sprouts', 'Vegetables', 'g', 'vegetable asian'),
('Baby Corn', 'Vegetables', 'g', 'vegetable asian'),
('Water Chestnut', 'Vegetables', 'pcs', 'vegetable asian'),
('Bamboo Shoots', 'Vegetables', 'g', 'vegetable asian'),
('Fresh Herbs (Cilantro)', 'Vegetables', 'g', 'herb fresh coriander'),
('Fresh Herbs (Parsley)', 'Vegetables', 'g', 'herb fresh'),
('Fresh Herbs (Mint)', 'Vegetables', 'g', 'herb fresh'),
('Fresh Herbs (Rosemary)', 'Vegetables', 'g', 'herb fresh'),
('Fresh Herbs (Thyme)', 'Vegetables', 'g', 'herb fresh'),
('Fresh Herbs (Dill)', 'Vegetables', 'g', 'herb fresh'),
('Fresh Herbs (Sage)', 'Vegetables', 'g', 'herb fresh'),

-- ===================== MORE DAIRY =====================
('Swiss Cheese', 'Dairy', 'g', 'dairy cheese'),
('Provolone', 'Dairy', 'g', 'dairy cheese italian'),
('Ricotta', 'Dairy', 'g', 'dairy cheese italian'),
('Mascarpone', 'Dairy', 'g', 'dairy cheese italian cream'),
('Blue Cheese', 'Dairy', 'g', 'dairy cheese'),
('Havarti', 'Dairy', 'g', 'dairy cheese'),
('Pepper Jack', 'Dairy', 'g', 'dairy cheese'),
('Colby Jack', 'Dairy', 'g', 'dairy cheese'),
('String Cheese', 'Dairy', 'pcs', 'dairy cheese snack'),
('Sliced American Cheese', 'Dairy', 'g', 'dairy cheese'),
('Shredded Cheese', 'Dairy', 'g', 'dairy cheese'),
('Whipped Cream', 'Dairy', 'ml', 'dairy cream topping'),
('Heavy Cream', 'Dairy', 'ml', 'dairy cream cooking'),
('Half and Half', 'Dairy', 'ml', 'dairy cream coffee'),
('Evaporated Milk', 'Dairy', 'ml', 'dairy milk canned'),
('Condensed Milk', 'Dairy', 'ml', 'dairy milk sweetened canned'),
('Soy Milk', 'Dairy', 'l', 'dairy alternative plant milk'),
('Coconut Yogurt', 'Dairy', 'g', 'dairy alternative yogurt plant'),
('Kefir', 'Dairy', 'ml', 'dairy probiotic fermented'),
('Ghee', 'Dairy', 'g', 'dairy butter clarified'),
('Egg Whites', 'Dairy', 'ml', 'dairy eggs protein'),
('Queso Fresco', 'Dairy', 'g', 'dairy cheese mexican'),
('Paneer', 'Dairy', 'g', 'dairy cheese indian'),
('Labneh', 'Dairy', 'g', 'dairy yogurt strained middle eastern'),

-- ===================== MORE MEAT =====================
('Chicken Drumstick', 'Meat', 'kg', 'meat poultry'),
('Ground Chicken', 'Meat', 'kg', 'meat poultry mince'),
('Chicken Sausage', 'Meat', 'pcs', 'meat poultry'),
('Rotisserie Chicken', 'Meat', 'pcs', 'meat poultry cooked'),
('Duck Breast', 'Meat', 'kg', 'meat poultry duck'),
('Ribeye Steak', 'Meat', 'kg', 'meat steak beef'),
('T-Bone Steak', 'Meat', 'kg', 'meat steak beef'),
('Filet Mignon', 'Meat', 'kg', 'meat steak beef tenderloin'),
('Flank Steak', 'Meat', 'kg', 'meat steak beef'),
('Beef Short Ribs', 'Meat', 'kg', 'meat beef ribs'),
('Beef Brisket', 'Meat', 'kg', 'meat beef bbq'),
('Stew Beef', 'Meat', 'kg', 'meat beef cubes'),
('Corned Beef', 'Meat', 'kg', 'meat beef cured'),
('Pork Tenderloin', 'Meat', 'kg', 'meat pork'),
('Pork Belly', 'Meat', 'kg', 'meat pork'),
('Pork Ribs', 'Meat', 'kg', 'meat pork bbq'),
('Ground Pork', 'Meat', 'kg', 'meat pork mince'),
('Italian Sausage', 'Meat', 'pcs', 'meat pork sausage'),
('Bratwurst', 'Meat', 'pcs', 'meat sausage german'),
('Chorizo', 'Meat', 'g', 'meat sausage spanish'),
('Hot Dog', 'Meat', 'pcs', 'meat sausage'),
('Ground Lamb', 'Meat', 'kg', 'meat lamb mince'),
('Lamb Shoulder', 'Meat', 'kg', 'meat lamb'),
('Rack of Lamb', 'Meat', 'kg', 'meat lamb'),
('Veal Cutlet', 'Meat', 'kg', 'meat veal'),
('Bison Burger', 'Meat', 'kg', 'meat ground'),
('Turkey Sausage', 'Meat', 'pcs', 'meat poultry sausage'),
('Deli Turkey', 'Meat', 'g', 'meat deli sliced'),
('Deli Ham', 'Meat', 'g', 'meat deli sliced'),
('Roast Beef Deli', 'Meat', 'g', 'meat deli sliced'),
('Pancetta', 'Meat', 'g', 'meat pork italian'),
('Canadian Bacon', 'Meat', 'g', 'meat pork'),
('Liver', 'Meat', 'g', 'meat organ offal'),

-- ===================== MORE SEAFOOD =====================
('Salmon (Canned)', 'Seafood', 'pcs', 'fish seafood tinned'),
('Canned Sardines in Oil', 'Seafood', 'pcs', 'fish seafood tinned'),
('Smoked Salmon', 'Seafood', 'g', 'fish seafood lox'),
('Swordfish', 'Seafood', 'kg', 'fish seafood'),
('Mahi Mahi', 'Seafood', 'kg', 'fish seafood'),
('Halibut', 'Seafood', 'kg', 'fish seafood white'),
('Trout', 'Seafood', 'kg', 'fish seafood'),
('Catfish', 'Seafood', 'kg', 'fish seafood'),
('Red Snapper', 'Seafood', 'kg', 'fish seafood'),
('Scallops', 'Seafood', 'kg', 'seafood shellfish'),
('Oysters', 'Seafood', 'pcs', 'seafood shellfish'),
('Crawfish', 'Seafood', 'kg', 'seafood shellfish'),
('Octopus', 'Seafood', 'kg', 'seafood'),
('Imitation Crab', 'Seafood', 'g', 'seafood surimi'),
('Fish Sticks', 'Seafood', 'pcs', 'fish seafood frozen'),
('Canned Crab', 'Seafood', 'pcs', 'seafood tinned'),

-- ===================== MORE GRAINS =====================
('Wild Rice', 'Grains', 'kg', 'grain rice'),
('Arborio Rice', 'Grains', 'kg', 'grain rice risotto'),
('Sushi Rice', 'Grains', 'kg', 'grain rice japanese'),
('Rice Noodles', 'Grains', 'g', 'grain noodle asian'),
('Egg Noodles', 'Grains', 'g', 'grain noodle'),
('Ramen Noodles', 'Grains', 'pcs', 'grain noodle asian'),
('Udon Noodles', 'Grains', 'g', 'grain noodle asian japanese'),
('Soba Noodles', 'Grains', 'g', 'grain noodle asian japanese buckwheat'),
('Vermicelli', 'Grains', 'g', 'grain noodle pasta thin'),
('Rigatoni', 'Grains', 'g', 'grain pasta'),
('Farfalle', 'Grains', 'g', 'grain pasta bow tie'),
('Orzo', 'Grains', 'g', 'grain pasta'),
('Gnocchi', 'Grains', 'g', 'grain pasta potato'),
('Tortellini', 'Grains', 'g', 'grain pasta stuffed'),
('Ravioli', 'Grains', 'g', 'grain pasta stuffed'),
('Pita Bread', 'Grains', 'pcs', 'grain bread middle eastern'),
('Ciabatta', 'Grains', 'pcs', 'grain bread italian'),
('Baguette', 'Grains', 'pcs', 'grain bread french'),
('English Muffin', 'Grains', 'pcs', 'grain bread breakfast'),
('Hamburger Buns', 'Grains', 'pcs', 'grain bread bun'),
('Hot Dog Buns', 'Grains', 'pcs', 'grain bread bun'),
('Croissant', 'Grains', 'pcs', 'grain bread pastry french'),
('Corn Tortilla', 'Grains', 'pcs', 'grain wrap flatbread mexican'),
('Flour Tortilla', 'Grains', 'pcs', 'grain wrap flatbread'),
('Breadcrumbs', 'Grains', 'g', 'grain bread coating'),
('Panko', 'Grains', 'g', 'grain bread coating japanese'),
('Croutons', 'Grains', 'g', 'grain bread salad'),
('Muesli', 'Grains', 'g', 'grain cereal breakfast'),
('Cream of Wheat', 'Grains', 'g', 'grain cereal breakfast hot'),
('Grits', 'Grains', 'g', 'grain cereal breakfast corn'),
('Buckwheat', 'Grains', 'g', 'grain'),
('Bulgur', 'Grains', 'g', 'grain wheat'),
('Farro', 'Grains', 'g', 'grain wheat'),
('Barley', 'Grains', 'g', 'grain'),
('Polenta', 'Grains', 'g', 'grain corn'),
('Cornmeal', 'Grains', 'g', 'grain corn baking'),
('Whole Wheat Flour', 'Grains', 'kg', 'grain baking flour'),
('Almond Flour', 'Grains', 'g', 'grain baking flour gluten free'),
('Coconut Flour', 'Grains', 'g', 'grain baking flour gluten free'),
('Self-Rising Flour', 'Grains', 'kg', 'grain baking flour'),

-- ===================== MORE SNACKS =====================
('Pistachios', 'Snacks', 'g', 'snack nut'),
('Pecans', 'Snacks', 'g', 'snack nut'),
('Macadamia Nuts', 'Snacks', 'g', 'snack nut'),
('Hazelnuts', 'Snacks', 'g', 'snack nut'),
('Mixed Nuts', 'Snacks', 'g', 'snack nut'),
('Sunflower Seeds', 'Snacks', 'g', 'snack seed'),
('Pumpkin Seeds', 'Snacks', 'g', 'snack seed'),
('Chia Seeds', 'Snacks', 'g', 'snack seed superfood'),
('Flax Seeds', 'Snacks', 'g', 'snack seed'),
('Beef Jerky', 'Snacks', 'g', 'snack meat dried'),
('Fruit Snacks', 'Snacks', 'pcs', 'snack gummy fruit'),
('Protein Bar', 'Snacks', 'pcs', 'snack energy bar'),
('White Chocolate', 'Snacks', 'g', 'snack chocolate'),
('Chocolate Chips', 'Snacks', 'g', 'snack baking chocolate'),
('Gummy Bears', 'Snacks', 'g', 'snack candy'),
('Marshmallows', 'Snacks', 'g', 'snack candy'),
('Pork Rinds', 'Snacks', 'g', 'snack'),
('Cheese Puffs', 'Snacks', 'g', 'snack cheesy'),
('Veggie Chips', 'Snacks', 'g', 'snack vegetable'),
('Seaweed Snacks', 'Snacks', 'g', 'snack asian nori'),
('Animal Crackers', 'Snacks', 'g', 'snack cookie'),
('Graham Crackers', 'Snacks', 'g', 'snack'),
('Rice Crackers', 'Snacks', 'g', 'snack asian'),

-- ===================== MORE BEVERAGES =====================
('Grape Juice', 'Beverages', 'l', 'beverage juice'),
('Pineapple Juice', 'Beverages', 'l', 'beverage juice'),
('Tomato Juice', 'Beverages', 'l', 'beverage juice vegetable'),
('V8 Juice', 'Beverages', 'l', 'beverage juice vegetable'),
('Ginger Ale', 'Beverages', 'l', 'beverage soda'),
('Root Beer', 'Beverages', 'l', 'beverage soda'),
('Tonic Water', 'Beverages', 'l', 'beverage mixer'),
('Club Soda', 'Beverages', 'l', 'beverage mixer carbonated'),
('Energy Drink', 'Beverages', 'ml', 'beverage energy'),
('Kombucha', 'Beverages', 'ml', 'beverage probiotic fermented'),
('Chai Tea', 'Beverages', 'pcs', 'beverage tea bags spice'),
('Chamomile Tea', 'Beverages', 'pcs', 'beverage tea bags herbal'),
('Espresso Pods', 'Beverages', 'pcs', 'beverage coffee capsule'),
('Decaf Coffee', 'Beverages', 'g', 'beverage coffee'),
('Hot Cocoa Mix', 'Beverages', 'g', 'beverage chocolate'),
('Matcha Powder', 'Beverages', 'g', 'beverage tea green japanese'),
('Lemon Juice (Bottled)', 'Beverages', 'ml', 'beverage juice citrus'),
('Protein Shake', 'Beverages', 'ml', 'beverage protein'),

-- ===================== MORE FROZEN =====================
('Frozen Mango', 'Frozen', 'g', 'frozen fruit tropical'),
('Frozen Spinach', 'Frozen', 'g', 'frozen vegetable leafy'),
('Frozen Edamame', 'Frozen', 'g', 'frozen vegetable soy'),
('Frozen Stir Fry Mix', 'Frozen', 'g', 'frozen vegetable asian'),
('Frozen Burrito', 'Frozen', 'pcs', 'frozen meal mexican'),
('Frozen Lasagna', 'Frozen', 'pcs', 'frozen meal pasta'),
('Frozen Mac and Cheese', 'Frozen', 'pcs', 'frozen meal pasta'),
('Frozen Pot Pie', 'Frozen', 'pcs', 'frozen meal'),
('Frozen Breakfast Sandwich', 'Frozen', 'pcs', 'frozen meal breakfast'),
('Frozen Pancakes', 'Frozen', 'pcs', 'frozen breakfast'),
('Frozen Hash Browns', 'Frozen', 'g', 'frozen potato breakfast'),
('Frozen Onion Rings', 'Frozen', 'g', 'frozen appetizer'),
('Frozen Mozzarella Sticks', 'Frozen', 'pcs', 'frozen appetizer cheese'),
('Frozen Spring Rolls', 'Frozen', 'pcs', 'frozen appetizer asian'),
('Frozen Pie Crust', 'Frozen', 'pcs', 'frozen baking'),
('Frozen Puff Pastry', 'Frozen', 'g', 'frozen baking pastry'),
('Frozen Cookie Dough', 'Frozen', 'g', 'frozen baking dessert'),
('Frozen Yogurt', 'Frozen', 'ml', 'frozen dessert'),
('Sorbet', 'Frozen', 'ml', 'frozen dessert fruit'),
('Ice Cream Sandwich', 'Frozen', 'pcs', 'frozen dessert'),
('Popsicle', 'Frozen', 'pcs', 'frozen dessert'),

-- ===================== MORE CONDIMENTS & SPICES =====================
('Sesame Oil', 'Condiments', 'ml', 'condiment oil asian'),
('Avocado Oil', 'Condiments', 'ml', 'condiment oil cooking'),
('Truffle Oil', 'Condiments', 'ml', 'condiment oil gourmet'),
('Sriracha', 'Condiments', 'ml', 'condiment sauce hot asian'),
('Fish Sauce', 'Condiments', 'ml', 'condiment sauce asian'),
('Oyster Sauce', 'Condiments', 'ml', 'condiment sauce asian'),
('Hoisin Sauce', 'Condiments', 'ml', 'condiment sauce asian'),
('Teriyaki Sauce', 'Condiments', 'ml', 'condiment sauce asian japanese'),
('Tahini', 'Condiments', 'g', 'condiment paste sesame middle eastern'),
('Harissa', 'Condiments', 'g', 'condiment paste spicy north african'),
('Gochujang', 'Condiments', 'g', 'condiment paste spicy korean'),
('Miso Paste', 'Condiments', 'g', 'condiment paste soy japanese'),
('Curry Paste', 'Condiments', 'g', 'condiment paste spicy thai'),
('Dijon Mustard', 'Condiments', 'ml', 'condiment sauce mustard'),
('Whole Grain Mustard', 'Condiments', 'ml', 'condiment sauce mustard'),
('Ranch Dressing', 'Condiments', 'ml', 'condiment sauce salad'),
('Italian Dressing', 'Condiments', 'ml', 'condiment sauce salad'),
('Caesar Dressing', 'Condiments', 'ml', 'condiment sauce salad'),
('Thousand Island', 'Condiments', 'ml', 'condiment sauce salad'),
('Apple Cider Vinegar', 'Condiments', 'ml', 'condiment vinegar'),
('Rice Vinegar', 'Condiments', 'ml', 'condiment vinegar asian'),
('Red Wine Vinegar', 'Condiments', 'ml', 'condiment vinegar'),
('Turmeric', 'Condiments', 'g', 'condiment seasoning spice'),
('Chili Powder', 'Condiments', 'g', 'condiment seasoning spice'),
('Garlic Powder', 'Condiments', 'g', 'condiment seasoning'),
('Onion Powder', 'Condiments', 'g', 'condiment seasoning'),
('Italian Seasoning', 'Condiments', 'g', 'condiment seasoning herb'),
('Taco Seasoning', 'Condiments', 'g', 'condiment seasoning mexican'),
('Cajun Seasoning', 'Condiments', 'g', 'condiment seasoning'),
('Bay Leaves', 'Condiments', 'g', 'condiment herb dried'),
('Nutmeg', 'Condiments', 'g', 'condiment seasoning spice'),
('Cloves', 'Condiments', 'g', 'condiment seasoning spice'),
('Cardamom', 'Condiments', 'g', 'condiment seasoning spice'),
('Coriander', 'Condiments', 'g', 'condiment seasoning spice'),
('Fennel Seeds', 'Condiments', 'g', 'condiment seasoning spice'),
('Red Pepper Flakes', 'Condiments', 'g', 'condiment seasoning spice hot'),
('Steak Sauce', 'Condiments', 'ml', 'condiment sauce'),
('Tartar Sauce', 'Condiments', 'ml', 'condiment sauce'),
('Relish', 'Condiments', 'ml', 'condiment pickle'),
('Capers', 'Condiments', 'g', 'condiment'),
('Olives', 'Condiments', 'g', 'condiment'),
('Pickles', 'Condiments', 'pcs', 'condiment fermented'),
('Sauerkraut', 'Condiments', 'g', 'condiment fermented'),
('Kimchi', 'Condiments', 'g', 'condiment fermented korean'),
('Almond Butter', 'Condiments', 'g', 'condiment spread nut'),
('Sunflower Butter', 'Condiments', 'g', 'condiment spread seed'),
('Marmalade', 'Condiments', 'g', 'condiment spread citrus'),
('Agave Syrup', 'Condiments', 'ml', 'condiment sweetener'),

-- ===================== MORE OTHER / PANTRY STAPLES =====================
('Powdered Sugar', 'Other', 'g', 'baking sweetener'),
('Yeast', 'Other', 'g', 'baking'),
('Cream of Tartar', 'Other', 'g', 'baking'),
('Food Coloring', 'Other', 'ml', 'baking'),
('Almond Extract', 'Other', 'ml', 'baking flavoring'),
('Peppermint Extract', 'Other', 'ml', 'baking flavoring'),
('Canned Black Beans', 'Other', 'pcs', 'tinned legume'),
('Canned Kidney Beans', 'Other', 'pcs', 'tinned legume'),
('Canned Pinto Beans', 'Other', 'pcs', 'tinned legume'),
('Canned White Beans', 'Other', 'pcs', 'tinned legume cannellini'),
('Canned Corn', 'Other', 'pcs', 'tinned vegetable'),
('Canned Green Beans', 'Other', 'pcs', 'tinned vegetable'),
('Canned Peas', 'Other', 'pcs', 'tinned vegetable'),
('Canned Pumpkin', 'Other', 'pcs', 'tinned vegetable'),
('Canned Coconut Cream', 'Other', 'ml', 'tinned cooking'),
('Diced Tomatoes', 'Other', 'pcs', 'tinned tomato'),
('Crushed Tomatoes', 'Other', 'pcs', 'tinned tomato'),
('Tomato Sauce', 'Other', 'pcs', 'tinned tomato'),
('Marinara Sauce', 'Other', 'pcs', 'sauce pasta tomato'),
('Alfredo Sauce', 'Other', 'pcs', 'sauce pasta cream'),
('Pesto', 'Other', 'g', 'sauce pasta basil'),
('Salsa Verde', 'Other', 'pcs', 'sauce green tomatillo'),
('Enchilada Sauce', 'Other', 'pcs', 'sauce mexican'),
('Beef Broth', 'Other', 'ml', 'stock soup'),
('Bone Broth', 'Other', 'ml', 'stock soup'),
('Canned Soup', 'Other', 'pcs', 'soup tinned'),
('Dried Black Beans', 'Other', 'g', 'legume dried'),
('Dried Chickpeas', 'Other', 'g', 'legume dried'),
('Split Peas', 'Other', 'g', 'legume dried'),
('Black-Eyed Peas', 'Other', 'g', 'legume dried'),
('Seitan', 'Other', 'g', 'protein plant wheat gluten'),
('Beyond Meat', 'Other', 'g', 'protein plant alternative'),
('Protein Powder', 'Other', 'g', 'protein supplement'),
('Nutritional Yeast', 'Other', 'g', 'vegan supplement'),
('Tapioca Starch', 'Other', 'g', 'baking thickener'),
('Arrowroot Powder', 'Other', 'g', 'baking thickener'),
('Soy Sauce (Low Sodium)', 'Other', 'ml', 'sauce asian'),
('Coconut Aminos', 'Other', 'ml', 'sauce alternative soy free'),
('Rice Paper', 'Other', 'pcs', 'wrapper asian'),
('Wonton Wrappers', 'Other', 'pcs', 'wrapper asian'),
('Spring Roll Wrappers', 'Other', 'pcs', 'wrapper asian'),
('Phyllo Dough', 'Other', 'g', 'baking pastry'),

-- ===================== HOUSEHOLD =====================
('Aluminum Foil', 'Other', 'pcs', 'household kitchen'),
('Plastic Wrap', 'Other', 'pcs', 'household kitchen'),
('Parchment Paper', 'Other', 'pcs', 'household kitchen baking'),
('Zip Lock Bags', 'Other', 'pcs', 'household kitchen storage'),
('Sponge', 'Other', 'pcs', 'household cleaning'),
('Laundry Detergent', 'Other', 'pcs', 'household cleaning'),
('All-Purpose Cleaner', 'Other', 'pcs', 'household cleaning'),
('Hand Soap', 'Other', 'ml', 'household cleaning'),
('Dishwasher Pods', 'Other', 'pcs', 'household cleaning'),
('Paper Napkins', 'Other', 'pcs', 'household'),
('Toilet Paper', 'Other', 'pcs', 'household bathroom'),
('Tissues', 'Other', 'pcs', 'household')

ON CONFLICT (name) DO NOTHING;
